name: Format Check

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  format-check:
    name: Check Code Format
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install black

    - name: Run format check
      run: |
        python3 scripts/format.py --path infini_train example --check

